[package]
name = "calculator-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4"
wasm-bindgen = "0.2.83"
serde_json = "1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]